version: '3'
services:
  products-service:
    build: ./products-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  orders-service:
    build: ./orders-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  admin-service:
    build: ./admin-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  image-service:
    build: ./image-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
